"""
Azure Key Vault envelope-mode KMS provider (Phase 3).

Encryption model
----------------
* Data is encrypted locally with **AES-256-GCM** using a per-message DEK
  (Data Encryption Key) generated by `os.urandom(32)`.
* The DEK is wrapped (encrypted) by the Key Vault KEK (Key Encryption Key)
  using **RSA-OAEP-256** — the KEK never leaves the Key Vault HSM.
* The Phase 2 AAD context is bound into the AES-GCM tag, so any attempt
  to decrypt the value under a different (tenant, config_path,
  classification) context fails the GCM authentication check.

Tag format (v1)
---------------
::

    kms:azkv-env:aes256gcm:v1:<key_id_b64u>|<wrapped_dek_b64u>|<nonce_b64u>|<aad_hash_hex>|<ciphertext_b64u>

The Phase-1 tag parser (`parse_tag`) keeps the whole pipe-delimited
string as the payload, then this provider splits it further. Pipe is
used because base64url (`A-Z a-z 0-9 - _ =`) never produces `|`.

Performance
-----------
Each ``decrypt`` call would otherwise require a Key Vault round-trip to
unwrap the DEK. We cache unwrap results in-process keyed by the wrapped
DEK bytes (TTL 15 min) — this is critical for paths like DbSphere
connection passwords that are decrypted on every query.
"""

from __future__ import annotations

import base64
import logging
import os
import threading
import time
from typing import Optional

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from open_webui.utils.kms.audit import parse_kek_version, record_op
from open_webui.utils.kms.base import (
    KMSProvider,
    build_tag,
    parse_tag,
)
from open_webui.utils.kms.classification import aad_hash, aad_serialize

log = logging.getLogger(__name__)


PAYLOAD_SEPARATOR = "|"
DEK_BYTES = 32  # AES-256
GCM_NONCE_BYTES = 12

# DEK cache TTL — balance between KV call volume and the impact window if
# the in-process DEK is later considered exposed (e.g. memory dump).
_DEFAULT_DEK_CACHE_TTL_SECS = 15 * 60


def _b64u_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _b64u_decode(text: str) -> bytes:
    pad = "=" * (-len(text) % 4)
    return base64.urlsafe_b64decode(text + pad)


class _DekCache:
    """In-process LRU-ish cache of unwrapped DEKs.

    Keyed by the wrapped DEK bytes (so different KEK versions / different
    KEK URIs naturally land in different slots). Fixed TTL with a hard cap
    on entries; eviction is "drop the oldest expired then drop the
    oldest live entry" — good enough for envelope-mode workloads which
    have a small working set.
    """

    def __init__(
        self, ttl_secs: int = _DEFAULT_DEK_CACHE_TTL_SECS, capacity: int = 256
    ) -> None:
        self._ttl = ttl_secs
        self._capacity = capacity
        self._lock = threading.Lock()
        self._entries: dict[bytes, tuple[bytes, float]] = {}

    def get(self, wrapped_dek: bytes) -> Optional[bytes]:
        now = time.monotonic()
        with self._lock:
            entry = self._entries.get(wrapped_dek)
            if entry is None:
                return None
            dek, expires_at = entry
            if expires_at < now:
                del self._entries[wrapped_dek]
                return None
            return dek

    def put(self, wrapped_dek: bytes, dek: bytes) -> None:
        now = time.monotonic()
        with self._lock:
            if len(self._entries) >= self._capacity:
                # Drop one expired entry first; if none, drop the oldest.
                expired = [k for k, (_, exp) in self._entries.items() if exp < now]
                if expired:
                    del self._entries[expired[0]]
                else:
                    oldest_key = min(self._entries, key=lambda k: self._entries[k][1])
                    del self._entries[oldest_key]
            self._entries[wrapped_dek] = (dek, now + self._ttl)

    def invalidate(self) -> None:
        """Drop all cached DEKs — call on KEK rotation or revoke."""
        with self._lock:
            self._entries.clear()


class CryptoClientFactory:
    """Lazy adapter for ``azure.keyvault.keys.crypto.CryptographyClient``.

    Indirected so tests can swap in a mock without touching Azure SDK.
    The provider only needs ``wrap_key(algorithm, key)`` and
    ``unwrap_key(algorithm, encrypted_key)``.

    Credential resolution order (first hit wins, evaluated at first .get()
    call so config edits take effect on next access):

      1. ``KMS_AZURE_TENANT_ID`` + ``KMS_AZURE_CLIENT_ID`` +
         ``KMS_AZURE_CLIENT_SECRET`` — dedicated Service Principal for KV
         access, typically used when the vault lives in a different tenant
         than the application's identity provider.
      2. ``MICROSOFT_CLIENT_TENANT_ID`` + ``MICROSOFT_CLIENT_ID`` +
         ``MICROSOFT_CLIENT_SECRET`` — re-use the existing Microsoft OAuth
         app for KV access. Only safe when the OAuth tenant is also the
         vault tenant.
      3. ``DefaultAzureCredential`` — Managed Identity in Azure-hosted
         environments, ``az login`` for local dev, environment variables
         (``AZURE_CLIENT_ID`` etc.) for generic CI/CD.

    Pre-built ``credential`` argument bypasses resolution entirely — used
    by tests to inject mocks without touching env vars.
    """

    def __init__(self, key_id: str, credential=None) -> None:
        self.key_id = key_id
        self._credential = credential
        self._client = None
        # Cache of CryptographyClient by key_id so the provider can
        # decrypt ciphertexts written under *previous* KEK versions
        # (or sibling keys in the same vault) after a rotation. The
        # cache size is naturally bounded — we only build entries for
        # key_ids that show up in actual envelope tags.
        self._aux_clients: dict[str, "object"] = {}

    def _resolve_credential(self):
        if self._credential is not None:
            return self._credential

        from azure.identity import (
            ClientSecretCredential,
            DefaultAzureCredential,
        )

        # Pull at call time so PersistentConfig hot-edits are picked up
        # on next factory rebuild without a process restart. Imported
        # lazily to keep config.py off the import path for tests that
        # inject a credential directly.
        try:
            from open_webui.config import (
                KMS_AZURE_CLIENT_ID,
                KMS_AZURE_CLIENT_SECRET,
                KMS_AZURE_TENANT_ID,
                MICROSOFT_CLIENT_ID,
                MICROSOFT_CLIENT_SECRET,
                MICROSOFT_CLIENT_TENANT_ID,
            )
        except Exception as e:
            log.warning(
                "azkv-env: could not load credential config (%s) — using DefaultAzureCredential",
                e,
            )
            return DefaultAzureCredential()

        kms_tenant = (KMS_AZURE_TENANT_ID.value or "").strip()
        kms_client = (KMS_AZURE_CLIENT_ID.value or "").strip()
        kms_secret = (KMS_AZURE_CLIENT_SECRET.value or "").strip()
        if kms_tenant and kms_client and kms_secret:
            log.debug("azkv-env: using KMS_AZURE_* dedicated Service Principal")
            return ClientSecretCredential(
                tenant_id=kms_tenant,
                client_id=kms_client,
                client_secret=kms_secret,
            )

        # MICROSOFT_CLIENT_* fallback only when the operator has NOT
        # indicated a KMS-specific tenant. If KMS_AZURE_TENANT_ID is set,
        # the operator explicitly named the KV tenant — falling through to
        # an OAuth credential whose tenant is unrelated would build a
        # cross-tenant credential and surface as
        # `additionally_allowed_tenants` errors at unwrap time. Better to
        # drop to DefaultAzureCredential (which reads AZURE_* env vars in
        # the chosen tenant) than to silently use the OAuth credential.
        if not kms_tenant:
            ms_tenant = (MICROSOFT_CLIENT_TENANT_ID.value or "").strip()
            ms_client = (MICROSOFT_CLIENT_ID.value or "").strip()
            ms_secret = (MICROSOFT_CLIENT_SECRET.value or "").strip()
            if ms_tenant and ms_client and ms_secret:
                log.debug(
                    "azkv-env: KMS_AZURE_* unset; using MICROSOFT_CLIENT_* OAuth credentials"
                )
                return ClientSecretCredential(
                    tenant_id=ms_tenant,
                    client_id=ms_client,
                    client_secret=ms_secret,
                )

        log.debug(
            "azkv-env: no static credentials configured; using DefaultAzureCredential"
        )
        return DefaultAzureCredential()

    def get(self):
        if self._client is None:
            from azure.keyvault.keys.crypto import CryptographyClient

            self._client = CryptographyClient(self.key_id, self._resolve_credential())
        return self._client

    def get_for(self, key_id: str):
        """Return a CryptographyClient bound to ``key_id``.

        Used during KEK rotation: an envelope written under the previous
        KEK URI still embeds that URI in its tag, and we have to unwrap
        with a client bound to *that* URI even after the provider's
        configured ``self.key_id`` has moved on. The same credential is
        reused — rotation switches the KEK, not the Service Principal.
        """
        if not key_id or key_id == self.key_id:
            return self.get()
        cached = self._aux_clients.get(key_id)
        if cached is not None:
            return cached

        from azure.keyvault.keys.crypto import CryptographyClient

        client = CryptographyClient(key_id, self._resolve_credential())
        self._aux_clients[key_id] = client
        return client


class AzureKeyVaultEnvelopeProvider(KMSProvider):
    name = "azkv-env"
    algo = "aes256gcm"

    def __init__(
        self,
        key_id: str,
        crypto_client_factory: Optional[CryptoClientFactory] = None,
        wrap_algorithm: Optional[str] = None,
        dek_cache: Optional[_DekCache] = None,
        restricted_key_id: Optional[str] = None,
        restricted_crypto_client_factory: Optional[CryptoClientFactory] = None,
    ) -> None:
        """
        :param key_id: Versioned KV key identifier
            (e.g. ``https://vault.vault.azure.net/keys/cloosphere-kek/abc123``).
            The version is captured in every emitted tag so KEK rotation
            doesn't break decrypt of older ciphertexts (KV keeps versions).
        :param crypto_client_factory: Override for tests. Production code
            passes None and relies on DefaultAzureCredential.
        :param wrap_algorithm: One of azure.keyvault.keys.crypto.KeyWrapAlgorithm
            string values. Defaults to ``rsa_oaep_256`` per Phase 0 §C1.
        :param dek_cache: Override for tests; defaults to a fresh _DekCache.
        :param restricted_key_id: Phase 4.4 — separate KEK URI for values
            with ``classification=='restricted'`` (PII / financial).
            ``None``/empty → all classifications share ``key_id``.
        :param restricted_crypto_client_factory: Override for tests.
        """
        if not key_id:
            raise ValueError(
                "AzureKeyVaultEnvelopeProvider requires a versioned key_id"
            )
        self.key_id = key_id
        self._factory = crypto_client_factory or CryptoClientFactory(key_id)
        self._wrap_algo = wrap_algorithm or "rsa_oaep_256"
        self._cache = dek_cache or _DekCache()

        # Restricted-tier KEK (Phase 4.4). When unset, ``encrypt`` falls
        # back to the default key_id for every classification — i.e. the
        # provider behaves identically to a single-KEK deployment.
        self.restricted_key_id = (restricted_key_id or "").strip() or None
        if self.restricted_key_id:
            self._restricted_factory = (
                restricted_crypto_client_factory
                or CryptoClientFactory(self.restricted_key_id)
            )
        else:
            self._restricted_factory = None

    # --- KMSProvider API --------------------------------------------------

    def _select_kek_for_context(
        self, context: Optional[dict]
    ) -> tuple[str, "CryptoClientFactory"]:
        """Phase 4.4 — pick the KEK for the upcoming wrap.

        Restricted (PII/financial) classification → ``restricted_key_id``
        when configured. Anything else → ``key_id`` (default tier).

        Returns ``(kek_uri, factory)``. The factory is the one bound to
        the chosen KEK so wrap_key hits the right vault.
        """
        if self.restricted_key_id and self._restricted_factory is not None:
            classification = (context or {}).get("classification") if context else None
            if classification == "restricted":
                return self.restricted_key_id, self._restricted_factory
        return self.key_id, self._factory

    def encrypt(self, plaintext: str, context: Optional[dict] = None) -> str:
        if not plaintext:
            return ""

        dek = os.urandom(DEK_BYTES)
        nonce = os.urandom(GCM_NONCE_BYTES)
        aad_bytes = aad_serialize(context) if context else b""
        aad_hex = aad_hash(context) if context else ""

        active_key_id, active_factory = self._select_kek_for_context(context)

        try:
            ciphertext = AESGCM(dek).encrypt(
                nonce, plaintext.encode("utf-8"), aad_bytes or None
            )

            client = active_factory.get()
            wrapped_dek = self._wrap_dek_with(client, dek)
            # Cache the freshly minted DEK so an immediate decrypt of the same
            # value (tests, retry logic) doesn't pay another KV round-trip.
            self._cache.put(wrapped_dek, dek)
        except Exception as e:
            # KV unreachable / permission error during wrap_key. Audit the
            # failure (operators need to see this) before re-raising.
            record_op(
                operation="wrap",
                success=False,
                context=context,
                kek_uri=active_key_id,
                kek_version=parse_kek_version(active_key_id),
                error_code=type(e).__name__,
            )
            raise

        record_op(
            operation="wrap",
            success=True,
            context=context,
            kek_uri=active_key_id,
            kek_version=parse_kek_version(active_key_id),
        )

        payload = PAYLOAD_SEPARATOR.join(
            [
                _b64u_encode(active_key_id.encode("utf-8")),
                _b64u_encode(wrapped_dek),
                _b64u_encode(nonce),
                aad_hex,
                _b64u_encode(ciphertext),
            ]
        )
        return build_tag(self.name, self.algo, payload)

    def decrypt(self, tagged: str, context: Optional[dict] = None) -> str:
        if not tagged:
            return ""

        parsed = parse_tag(tagged)
        if parsed is None:
            raise ValueError("AzureKeyVaultEnvelopeProvider received non-tagged value")
        if parsed.provider != self.name or parsed.algo != self.algo:
            raise ValueError(
                f"AzureKeyVaultEnvelopeProvider got tag for {parsed.provider}/{parsed.algo}"
            )

        try:
            key_id_b64, wrapped_b64, nonce_b64, aad_hex, ct_b64 = parsed.payload.split(
                PAYLOAD_SEPARATOR
            )
        except ValueError as e:
            raise ValueError(f"Malformed envelope payload: {e}") from None

        wrapped_dek = _b64u_decode(wrapped_b64)
        nonce = _b64u_decode(nonce_b64)
        ciphertext = _b64u_decode(ct_b64)

        # Fast pre-check: if the caller supplied a context, its hash must
        # match what was written. This rejects misrouted contexts before
        # we burn a KV round-trip on unwrap.
        aad_bytes = aad_serialize(context) if context else b""
        if context is not None and aad_hex and aad_hash(context) != aad_hex:
            record_op(
                operation="unwrap",
                success=False,
                context=context,
                kek_uri=self.key_id,
                kek_version=parse_kek_version(self.key_id),
                error_code="AAD_MISMATCH",
            )
            raise ValueError(
                "AAD context mismatch — cannot decrypt value written under a different context"
            )

        # Cache hit avoids a KV round-trip — that means no actual KMS trust
        # boundary crossing happened, so we don't audit it. Hot paths
        # (DbSphere queries) repeatedly unwrap the same DEK, and auditing
        # every such call would dwarf the actual workload's DB writes.
        # Cache misses (real KV unwrap) are audited unconditionally.
        cache_hit = True
        dek = self._cache.get(wrapped_dek)
        if dek is None:
            cache_hit = False
            try:
                dek = self._unwrap_dek(wrapped_dek, key_id_b64)
                self._cache.put(wrapped_dek, dek)
            except Exception as e:
                record_op(
                    operation="unwrap",
                    success=False,
                    context=context,
                    kek_uri=self.key_id,
                    kek_version=parse_kek_version(self.key_id),
                    error_code=type(e).__name__,
                )
                raise

        try:
            plaintext = (
                AESGCM(dek)
                .decrypt(nonce, ciphertext, aad_bytes or None)
                .decode("utf-8")
            )
        except Exception as e:
            record_op(
                operation="unwrap",
                success=False,
                context=context,
                kek_uri=self.key_id,
                kek_version=parse_kek_version(self.key_id),
                error_code="GCM_TAG_FAIL",
            )
            # AES-GCM tag failure surfaces as InvalidTag / cryptography
            # error; normalize to ValueError so callers can match on it
            # without depending on cryptography internals.
            raise ValueError(
                f"Envelope decrypt failed (AAD or ciphertext mismatch): {e}"
            ) from None

        if not cache_hit:
            record_op(
                operation="unwrap",
                success=True,
                context=context,
                kek_uri=self.key_id,
                kek_version=parse_kek_version(self.key_id),
            )
        return plaintext

    def health_check(self) -> tuple[bool, str]:
        # Probe both tiers when restricted is configured so the admin
        # gets one combined OK/FAIL message for the whole envelope path.
        # Each probe wraps a throwaway DEK — cheapest call that still
        # exercises auth + network + the KEK's wrap permission.
        try:
            client = self._factory.get()
            self._wrap_dek_with(client, os.urandom(DEK_BYTES))
            record_op(
                operation="health_check",
                success=True,
                kek_uri=self.key_id,
                kek_version=parse_kek_version(self.key_id),
            )
        except Exception as e:
            record_op(
                operation="health_check",
                success=False,
                kek_uri=self.key_id,
                kek_version=parse_kek_version(self.key_id),
                error_code=type(e).__name__,
            )
            return False, f"azkv-env (default): {e!r}"

        if self.restricted_key_id and self._restricted_factory is not None:
            try:
                rclient = self._restricted_factory.get()
                self._wrap_dek_with(rclient, os.urandom(DEK_BYTES))
                record_op(
                    operation="health_check",
                    success=True,
                    kek_uri=self.restricted_key_id,
                    kek_version=parse_kek_version(self.restricted_key_id),
                    classification="restricted",
                )
            except Exception as e:
                record_op(
                    operation="health_check",
                    success=False,
                    kek_uri=self.restricted_key_id,
                    kek_version=parse_kek_version(self.restricted_key_id),
                    classification="restricted",
                    error_code=type(e).__name__,
                )
                return False, f"azkv-env (restricted): {e!r}"
            return (
                True,
                f"azkv-env: ok (default={self.key_id}, restricted={self.restricted_key_id})",
            )

        return True, f"azkv-env: ok (key={self.key_id})"

    # --- KEK wrap/unwrap --------------------------------------------------

    def _wrap_dek(self, dek: bytes) -> bytes:
        client = self._factory.get()
        return self._wrap_dek_with(client, dek)

    def _wrap_dek_with(self, client, dek: bytes) -> bytes:
        from azure.keyvault.keys.crypto import KeyWrapAlgorithm

        algo = getattr(KeyWrapAlgorithm, self._wrap_algo)
        result = client.wrap_key(algo, dek)
        return bytes(result.encrypted_key)

    def _unwrap_dek(self, wrapped_dek: bytes, key_id_b64: str) -> bytes:
        from azure.keyvault.keys.crypto import KeyWrapAlgorithm

        # The tag carries the original key_id (with version). Three
        # cases:
        #   * embedded == self.key_id → default tier, hit the primary
        #     factory (covers fresh writes + same-tier prior versions).
        #   * embedded == self.restricted_key_id → Phase 4.4 PII tier,
        #     route through the restricted factory.
        #   * anything else → a *previous* KEK URI that the factory
        #     hasn't seen yet (typically post-rotation legacy ciphertext);
        #     ``CryptoClientFactory.get_for`` builds a client on demand.
        # KV keeps disabled KEK versions decryptable so this Just Works
        # as long as the rotation policy didn't *delete* the old key.
        embedded_key_id = _b64u_decode(key_id_b64).decode("utf-8")

        if (
            self.restricted_key_id
            and self._restricted_factory is not None
            and embedded_key_id == self.restricted_key_id
        ):
            client = self._restricted_factory.get()
        else:
            if embedded_key_id != self.key_id:
                log.debug(
                    "azkv-env: unwrapping ciphertext under prior KEK %r (current=%r)",
                    embedded_key_id,
                    self.key_id,
                )
            client = self._factory.get_for(embedded_key_id)

        algo = getattr(KeyWrapAlgorithm, self._wrap_algo)
        result = client.unwrap_key(algo, wrapped_dek)
        return bytes(result.key)
