<script lang="ts">
	import { onMount, getContext, createEventDispatcher } from 'svelte';
	import { browser } from '$app/environment';
	import { toast } from 'svelte-sonner';
	import { goto } from '$app/navigation';
	import { trackAIGeneration, clearAITask } from '$lib/stores/ai-generation';

	const i18n = getContext('i18n');
	const dispatch = createEventDispatcher();

	import { WEBUI_NAME, user, models, showSidebar } from '$lib/stores';

	$: canWrite = $user?.role === 'admin' || $user?.permissions?.workspace?.agent_flows === 'write';
	import {
		createAgentFlow,
		updateAgentFlow,
		getAgentFlowById,
		validateAgentFlow,
		exportAgentFlow,
		importAgentFlow,
		checkFlowIdAvailable,
		autoBuildAgentFlow,
		autoBuildFlowChat
	} from '$lib/apis/agent-flows';
	import type { AgentFlow, FlowData, AgentFlowForm } from '$lib/apis/agent-flows';
	import Spinner from '$lib/components/common/Spinner.svelte';

	// AI Chat Panel — Multi-turn ReAct with Human-in-the-Loop
	let showAIChat = false;
	let aiChatInput = '';
	let aiChatModel = '';
	let aiChatLoading = false;
	let aiFlowId = '';
	let aiChatHeight = 320; // Track generated flow for updates

	type ChatMsg = {
		role: 'user' | 'ai';
		content: string;
		loading?: boolean;
		buttons?: Array<{ label: string; value: string }>;
	};
	let aiChatMessages: ChatMsg[] = [];
	let conversationHistory: Array<{ role: string; content: string }> = [];
	let pendingTaskId = '';

	// Derive model options from store (base LLM models only)
	$: aiModelOptions = ($models ?? [])
		.filter((m: any) => m.id && m.name && !m?.info?.base_model_id && !m?.preset && m?.owned_by !== 'arena' && m?.owned_by !== 'agent_flow')
		.map((m: any) => ({ id: m.id, label: m.name }));

	// Load existing chat history when editing a flow
	function loadChatHistory(flowMeta: any) {
		if (flowMeta?.ai_chat_history) {
			conversationHistory = flowMeta.ai_chat_history;
			aiChatMessages = conversationHistory.map((m: any) => ({
				role: m.role === 'assistant' ? 'ai' as const : 'user' as const,
				content: m.content,
			}));
		}
	}

	function handleButtonClick(value: string) {
		console.log('[FlowEditor] Button clicked:', value);
		// Remove buttons from the last message to prevent re-clicking
		aiChatMessages = aiChatMessages.map(m =>
			m.buttons ? { ...m, buttons: undefined } : m
		);
		sendAIChat(value);
	}

	async function sendAIChat(overrideMsg?: string | Event) {
		// Ignore Event objects (from on:click handlers)
		const msg = typeof overrideMsg === 'string' ? overrideMsg.trim() : '';
		const userMsg = msg || aiChatInput.trim();
		if (!userMsg || aiChatLoading) return;
		aiChatInput = '';

		// Add to histories
		conversationHistory = [...conversationHistory, { role: 'user', content: userMsg }];
		aiChatMessages = [...aiChatMessages, { role: 'user', content: userMsg }];
		aiChatMessages = [...aiChatMessages, { role: 'ai', content: '', loading: true }];
		aiChatLoading = true;

		// API 호출을 글로벌 트래커에 등록 — 페이지 이동 후에도 toast 표시
		const promise = autoBuildFlowChat(
			localStorage.token,
			conversationHistory,
			aiChatModel,
			flowName || '',
			aiFlowId || flowId || ''
		);

		pendingTaskId = trackAIGeneration('flow', flowName || 'new', promise, {
			success: $i18n.t('Flow generated by AI'),
			error: $i18n.t('Flow AI generation failed'),
		});

		try {
			const result = await promise;

			// Add AI response to history
			const aiMsg = result.assistant_message || '';
			conversationHistory = [...conversationHistory, { role: 'assistant', content: aiMsg }];

			// Remove loading, add real message
			aiChatMessages = aiChatMessages.slice(0, -1);

			if (result.pending_input && result.pending_input.options?.length > 0) {
				// LLM is asking user — show buttons
				aiChatMessages = [...aiChatMessages, {
					role: 'ai',
					content: aiMsg,
					buttons: result.pending_input.options.map((o: string) => ({ label: o, value: o })),
				}];
			} else {
				aiChatMessages = [...aiChatMessages, { role: 'ai', content: aiMsg }];
			}

			// Update flow if generated
			if (result.flow_data && result.flow_data.nodes?.length > 0) {
				flowData = result.flow_data;
				flowData = { ...flowData };
				if (result.flow_name && !flowName) flowName = result.flow_name;
				if (result.flow_description && !flowDescription) flowDescription = result.flow_description;
				if (result.flow_id) aiFlowId = result.flow_id;
			}

			// toast는 trackAIGeneration에서 처리됨
			clearAITask(pendingTaskId);
		} catch (e: any) {
			aiChatMessages = aiChatMessages.slice(0, -1);
			aiChatMessages = [...aiChatMessages, {
				role: 'ai',
				content: `❌ ${e?.toString() || 'Error'}`,
			}];
			clearAITask(pendingTaskId);
		} finally {
			aiChatLoading = false;
			pendingTaskId = '';
		}
	}
	import { compressImage } from '$lib/utils';
	import { brandingUrls } from '$lib/stores/branding';
	import WorkspaceTagSelector from '$lib/components/common/WorkspaceTagSelector.svelte';
	import AccessControlModal from '$lib/components/workspace/common/AccessControlModal.svelte';

	import NodePalette from '$lib/components/workspace/AgentFlows/NodePalette.svelte';
	import NodeConfigPanel from '$lib/components/workspace/AgentFlows/NodeConfigPanel.svelte';
	import FlowToolbar from '$lib/components/workspace/AgentFlows/FlowToolbar.svelte';
	import Button from '$lib/components/common/Button.svelte';
	import Selector from '$lib/components/common/Selector.svelte';
	import LockClosed from '$lib/components/icons/LockClosed.svelte';

	// Dynamic import for FlowBuilder to avoid SSR issues with @xyflow/svelte
	let FlowBuilder: any = null;
	let Node: any = null;

	// Props
	export let flowId: string | null = null;
	export let mode: 'create' | 'edit' = 'create';

	// State
	let flow: AgentFlow | null = null;
	let flowName = '';
	let flowCustomId = '';
	let flowIdAvailable: boolean | null = null;
	let flowIdChecking = false;
	let flowDescription = '';
	let flowData: FlowData = { nodes: [], edges: [], variables: {} };
	let isActive = true;
	let profileImageUrl = $brandingUrls.favicon;

	let selectedNode: any = null;
	let upstreamNodes: any[] = [];
	let stateKeys: Array<{ key: string; source: string; nodeId: string; type: string }> = [];
	let isValid = true;
	let isSaving = false;
	let loaded = false;

	let accessControl: any = null;
	let showAccessControlModal = false;
	let tagSelector: any;

	let flowBuilderRef: FlowBuilder;
	let filesInputElement: HTMLInputElement;
	let inputFiles: FileList | null = null;

	// Handle image upload
	$: if (inputFiles && inputFiles.length > 0) {
		const reader = new FileReader();
		reader.onload = async (event) => {
			const originalSrc = event.target?.result as string;
			try {
				const compressedSrc = await compressImage(originalSrc);
				profileImageUrl = compressedSrc;
			} catch (e) {
				console.error('Failed to compress image:', e);
				profileImageUrl = originalSrc;
			}
			inputFiles = null;
		};
		reader.readAsDataURL(inputFiles[0]);
	}

	// Flow ID validation
	let flowIdCheckTimer: ReturnType<typeof setTimeout>;

	function handleFlowIdInput() {
		flowIdAvailable = null;
		clearTimeout(flowIdCheckTimer);

		const id = flowCustomId.trim().toLowerCase();
		if (!id || id.length < 2) return;

		if (!/^[a-z0-9][a-z0-9_-]*$/.test(id)) {
			flowIdAvailable = null;
			return;
		}

		flowIdChecking = true;
		flowIdCheckTimer = setTimeout(async () => {
			try {
				const result = await checkFlowIdAvailable(localStorage.token, id);
				flowIdAvailable = result.available;
			} catch {
				flowIdAvailable = null;
			} finally {
				flowIdChecking = false;
			}
		}, 400);
	}

	// Load flow if editing
	onMount(async () => {
		// Dynamically import FlowBuilder to avoid SSR issues
		if (browser) {
			const module = await import('$lib/components/workspace/AgentFlows/FlowBuilder.svelte');
			FlowBuilder = module.default;
		}

		if (mode === 'edit' && flowId) {
			try {
				flow = await getAgentFlowById(localStorage.token, flowId);
				if (flow) {
					flowName = flow.name;
					flowDescription = flow.description || '';
					flowData = flow.flow_data || { nodes: [], edges: [], variables: {} };
					isActive = flow.is_active;
					profileImageUrl = (flow.meta as any)?.profile_image_url || $brandingUrls.favicon;
					accessControl = flow.access_control ?? null;
					// Restore AI chat history if exists
					loadChatHistory(flow.meta);
				}
			} catch (e) {
				console.error('Failed to load flow:', e);
				toast.error($i18n.t('Failed to load flow'));
			}
		}
		loaded = true;
	});

	// Handlers
	async function handleSave() {
		if (!flowName.trim()) {
			toast.error($i18n.t('Please enter a flow name'));
			return;
		}

		// 생성 시 ID 필수 검증
		if (mode === 'create') {
			const id = flowCustomId.trim().toLowerCase();
			if (!id) {
				toast.error($i18n.t('Please enter a Flow ID'));
				return;
			}
			if (!/^[a-z0-9][a-z0-9_-]*$/.test(id)) {
				toast.error($i18n.t('Flow ID can only contain lowercase letters, numbers, and hyphens'));
				return;
			}
			if (id.length < 2 || id.length > 50) {
				toast.error($i18n.t('Flow ID must be between 2 and 50 characters'));
				return;
			}
			if (flowIdAvailable === false) {
				toast.error($i18n.t('This Flow ID is already in use'));
				return;
			}
		}

		isSaving = true;
		try {
			// 태그 변경사항 커밋 (save가 페이지 이동할 수 있으므로 먼저 실행)
			if (tagSelector?.commitChanges) {
				try {
					await tagSelector.commitChanges();
				} catch (e) {
					console.error('Failed to commit tag changes:', e);
				}
			}

			const currentFlowData = flowBuilderRef?.getFlowData() || flowData;

			const formData: AgentFlowForm = {
				id: flowCustomId.trim().toLowerCase(),
				name: flowName,
				description: flowDescription,
				flow_data: currentFlowData,
				is_active: isActive,
				access_control: accessControl,
				meta: {
					profile_image_url: profileImageUrl
				}
			};

			if (mode === 'create') {
				const newFlow = await createAgentFlow(localStorage.token, formData);
				if (newFlow) {
					toast.success($i18n.t('Flow created successfully'));
					goto(`/workspace/flows/${newFlow.id}`);
				}
			} else if (flowId) {
				const updatedFlow = await updateAgentFlow(localStorage.token, flowId, formData);
				if (updatedFlow) {
					flow = updatedFlow;
					toast.success($i18n.t('Flow saved successfully'));
				}
			}
		} catch (e) {
			console.error('Failed to save flow:', e);
			toast.error($i18n.t('Failed to save flow'));
		} finally {
			isSaving = false;
		}
	}

	async function handleValidate() {
		const currentFlowData = flowBuilderRef?.getFlowData() || flowData;

		try {
			const result = await validateAgentFlow(localStorage.token, currentFlowData);
			isValid = result.valid;

			if (result.valid) {
				toast.success($i18n.t('Flow is valid'));
			} else {
				const errorMessages = result.errors.map((e) => e.message).join('\n');
				toast.error($i18n.t('Validation errors') + ':\n' + errorMessages);
			}

			if (result.warnings.length > 0) {
				const warningMessages = result.warnings.map((w) => w.message).join('\n');
				toast.warning($i18n.t('Warnings') + ':\n' + warningMessages);
			}
		} catch (e) {
			console.error('Validation failed:', e);
			toast.error($i18n.t('Validation failed'));
		}
	}

	async function handleExport() {
		if (!flowId) {
			// Export current unsaved flow
			const currentFlowData = flowBuilderRef?.getFlowData() || flowData;
			const exportData = {
				version: '1.0',
				type: 'agent_flow',
				name: flowName || 'Untitled Flow',
				description: flowDescription,
				flow_data: currentFlowData
			};

			const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
			const url = URL.createObjectURL(blob);
			const a = document.createElement('a');
			a.href = url;
			a.download = `${flowName || 'flow'}.json`;
			a.click();
			URL.revokeObjectURL(url);
			return;
		}

		try {
			const exportData = await exportAgentFlow(localStorage.token, flowId);
			const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
			const url = URL.createObjectURL(blob);
			const a = document.createElement('a');
			a.href = url;
			a.download = `${flowName || 'flow'}.json`;
			a.click();
			URL.revokeObjectURL(url);
			toast.success($i18n.t('Flow exported successfully'));
		} catch (e) {
			console.error('Export failed:', e);
			toast.error($i18n.t('Export failed'));
		}
	}

	function handleImport() {
		const input = document.createElement('input');
		input.type = 'file';
		input.accept = '.json';
		input.onchange = async (e) => {
			const file = (e.target as HTMLInputElement).files?.[0];
			if (!file) return;

			try {
				const text = await file.text();
				const data = JSON.parse(text);

				if (data.type !== 'agent_flow') {
					toast.error($i18n.t('Invalid flow file'));
					return;
				}

				// Update local state with imported data
				flowName = data.name || flowName;
				flowDescription = data.description || flowDescription;
				flowData = data.flow_data || { nodes: [], edges: [], variables: {} };

				toast.success($i18n.t('Flow imported successfully'));
			} catch (e) {
				console.error('Import failed:', e);
				toast.error($i18n.t('Failed to import flow'));
			}
		};
		input.click();
	}

	function handleBack() {
		goto('/workspace/flows');
	}

	function handleNodeSelect(event: CustomEvent<{ node: any; upstreamNodes?: any[]; stateKeys?: typeof stateKeys }>) {
		selectedNode = event.detail.node;
		upstreamNodes = event.detail.upstreamNodes || [];
		stateKeys = event.detail.stateKeys || [];
	}

	function handleNodeUpdate(event: CustomEvent<{ nodeId: string; data: any }>) {
		flowBuilderRef?.updateNodeData(event.detail.nodeId, event.detail.data);
	}

	function handleNodeDelete(event: CustomEvent<{ nodeId: string }>) {
		flowBuilderRef?.deleteNode(event.detail.nodeId);
		selectedNode = null;
	}

	function handleFlowChange(event: CustomEvent<{ flowData: FlowData }>) {
		flowData = event.detail.flowData;
	}
</script>

<svelte:head>
	<title>
		{mode === 'create' ? $i18n.t('Create Flow') : flowName || $i18n.t('Edit Flow')} | {$WEBUI_NAME}
	</title>
</svelte:head>

{#if loaded}
	<div class="h-full flex flex-col bg-gray-50 dark:bg-gray-900">
		<AccessControlModal
			bind:show={showAccessControlModal}
			bind:accessControl
			accessRoles={['read', 'write']}
			allowPublic={$user?.role === 'admin'}
		/>

		<!-- Toolbar -->
		<FlowToolbar
			flowName={flowName}
			{isValid}
			{isSaving}
			{mode}
			{canWrite}
			canUndo={false}
			canRedo={false}
			on:save={handleSave}
			on:validate={handleValidate}
			on:export={handleExport}
			on:import={handleImport}
			on:back={handleBack}
		>
			<svelte:fragment slot="actions">
				{#if mode === 'edit' && flowId}
					<WorkspaceTagSelector bind:this={tagSelector} resourceType="flow" resourceId={flowId} />
				{/if}

				{#if canWrite}
					<Button kind="outlined" size="sm" on:click={() => { showAccessControlModal = true; }}>
						<svelte:fragment slot="prefix">
							<LockClosed strokeWidth="2.5" className="size-3.5" />
						</svelte:fragment>
						{$i18n.t('Access')}
					</Button>
				{/if}
			</svelte:fragment>
		</FlowToolbar>

		<!-- Main content -->
		<div class="flex-1 flex overflow-hidden">
			<!-- Left sidebar: Node palette -->
			<div class="w-64 border-r border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 overflow-hidden flex flex-col">
				<!-- Hidden file input for image upload -->
				<input
					bind:this={filesInputElement}
					bind:files={inputFiles}
					type="file"
					hidden
					accept="image/*"
				/>

				<!-- Flow icon and name input -->
				<div class="p-4 border-b border-gray-200 dark:border-gray-700">
					<!-- Flow Icon -->
					<div class="flex items-center gap-3 mb-3">
						<button
							class="rounded-lg flex shrink-0 items-center {profileImageUrl !== $brandingUrls.favicon
								? 'bg-transparent'
								: 'bg-white dark:bg-gray-800'} shadow-md group relative"
							type="button"
							on:click={() => {
								filesInputElement.click();
							}}
						>
							<img
								src={profileImageUrl}
								alt="flow icon"
								class="rounded-lg size-12 object-cover shrink-0"
							/>

							<div class="absolute bottom-0 right-0 z-10">
								<div class="m-0.5">
									<div
										class="shadow-md p-0.5 rounded-full border border-white bg-gray-800 text-white group-hover:bg-gray-600 transition dark:border-gray-700 dark:bg-white dark:group-hover:bg-gray-200 dark:text-black"
									>
										<svg
											xmlns="http://www.w3.org/2000/svg"
											viewBox="0 0 16 16"
											fill="currentColor"
											class="size-3"
										>
											<path
												fill-rule="evenodd"
												d="M2 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V4Zm10.5 5.707a.5.5 0 0 0-.146-.353l-1-1a.5.5 0 0 0-.708 0L9.354 9.646a.5.5 0 0 1-.708 0L6.354 7.354a.5.5 0 0 0-.708 0l-2 2a.5.5 0 0 0-.146.353V12a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5V9.707ZM12 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"
												clip-rule="evenodd"
											/>
										</svg>
									</div>
								</div>
							</div>

							<div
								class="absolute top-0 bottom-0 left-0 right-0 bg-white dark:bg-black rounded-lg opacity-0 group-hover:opacity-20 transition"
							></div>
						</button>

						<div class="flex-1 min-w-0">
							<input
								type="text"
								bind:value={flowName}
								class="w-full px-2 py-1 text-sm font-semibold rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
								placeholder={$i18n.t('Enter flow name')}
							/>
							{#if profileImageUrl !== $brandingUrls.favicon}
								<button
									class="text-xs text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 mt-1"
									on:click={() => {
										profileImageUrl = $brandingUrls.favicon;
									}}
								>
									{$i18n.t('Reset Image')}
								</button>
							{/if}
						</div>
					</div>

					{#if mode === 'create'}
						<div class="mt-2">
							<label class="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">
								{$i18n.t('Flow ID')}
							</label>
							<div class="relative">
								<input
									type="text"
									bind:value={flowCustomId}
									on:input={handleFlowIdInput}
									class="w-full px-3 py-1.5 text-sm rounded-lg border bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 focus:border-transparent {flowIdAvailable === false ? 'border-red-400 dark:border-red-600' : flowIdAvailable === true ? 'border-green-400 dark:border-green-600' : 'border-gray-200 dark:border-gray-700'}"
									placeholder={$i18n.t('e.g. my-sales-flow')}
									maxlength="50"
								/>
								{#if flowIdChecking}
									<div class="absolute right-2 top-1/2 -translate-y-1/2">
										<svg class="animate-spin size-4 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
											<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
											<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
										</svg>
									</div>
								{:else if flowIdAvailable === true}
									<div class="absolute right-2 top-1/2 -translate-y-1/2 text-green-500">
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
											<path fill-rule="evenodd" d="M12.416 3.376a.75.75 0 0 1 .208 1.04l-5 7.5a.75.75 0 0 1-1.154.114l-3-3a.75.75 0 0 1 1.06-1.06l2.353 2.353 4.493-6.74a.75.75 0 0 1 1.04-.207Z" clip-rule="evenodd" />
										</svg>
									</div>
								{:else if flowIdAvailable === false}
									<div class="absolute right-2 top-1/2 -translate-y-1/2 text-red-500">
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
											<path d="M5.28 4.22a.75.75 0 0 0-1.06 1.06L6.94 8l-2.72 2.72a.75.75 0 1 0 1.06 1.06L8 9.06l2.72 2.72a.75.75 0 1 0 1.06-1.06L9.06 8l2.72-2.72a.75.75 0 0 0-1.06-1.06L8 6.94 5.28 4.22Z" />
											</svg>
									</div>
								{/if}
							</div>
							{#if flowCustomId.trim() && !/^[a-z0-9][a-z0-9_-]*$/.test(flowCustomId.trim().toLowerCase())}
								<p class="text-xs text-red-500 mt-0.5">{$i18n.t('Only lowercase letters, numbers, and hyphens allowed')}</p>
							{:else if flowIdAvailable === false}
								<p class="text-xs text-red-500 mt-0.5">{$i18n.t('This Flow ID is already in use')}</p>
							{:else}
								<p class="text-xs text-gray-400 mt-0.5">{$i18n.t('Lowercase letters, numbers, hyphens only (2-50 chars)')}</p>
							{/if}
						</div>
					{/if}

					<label class="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">
						{$i18n.t('Description')}
					</label>
					<textarea
						bind:value={flowDescription}
						rows="2"
						class="w-full px-3 py-2 text-sm rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
						placeholder={$i18n.t('Enter description')}
					></textarea>
				</div>

				<!-- Node palette -->
				<div class="flex-1 overflow-y-auto">
					<NodePalette />
				</div>
			</div>

			<!-- Canvas + AI Chat -->
			<div class="flex-1 overflow-hidden flex flex-col">
				<!-- Canvas -->
				<div class="flex-1 overflow-hidden relative">
					{#if FlowBuilder}
						<svelte:component
							this={FlowBuilder}
							bind:this={flowBuilderRef}
							{flowData}
							on:nodeselect={handleNodeSelect}
							on:change={handleFlowChange}
						/>
					{:else}
						<div class="flex items-center justify-center h-full">
							<div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 dark:border-white"></div>
						</div>
					{/if}

					<!-- AI Chat Toggle Button (viewport-fixed) -->
					{#if !showAIChat}
						<button
							type="button"
							class="fixed bottom-4 right-4 z-40 flex items-center gap-2 px-4 py-2.5 rounded-full bg-violet-600 hover:bg-violet-700 text-white shadow-lg transition-all hover:shadow-xl hover:scale-105"
							on:click={() => { showAIChat = true; }}
						>
							<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
							</svg>
							<span class="text-sm font-medium">{$i18n.t('AI Assistant')}</span>
						</button>
					{/if}
				</div>

				<!-- AI Chat Panel (fixed right side) -->
				{#if showAIChat}
					<div
						class="fixed bottom-0 right-0 border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 flex flex-col shadow-2xl z-50"
						style="height: {aiChatHeight}px; min-height: 280px; max-height: calc(100vh - 60px); left: {$showSidebar ? '260px' : '68px'};"
					>
						<!-- Resize handle -->
						<div
							class="h-1.5 cursor-ns-resize bg-gray-100 dark:bg-gray-800 hover:bg-violet-200 dark:hover:bg-violet-900/40 transition-colors flex items-center justify-center"
							on:mousedown={(e) => {
								const startY = e.clientY;
								const startH = aiChatHeight;
								const onMove = (ev) => {
									aiChatHeight = Math.max(280, Math.min(window.innerHeight - 60, startH - (ev.clientY - startY)));
								};
								const onUp = () => {
									window.removeEventListener('mousemove', onMove);
									window.removeEventListener('mouseup', onUp);
								};
								window.addEventListener('mousemove', onMove);
								window.addEventListener('mouseup', onUp);
							}}
							role="separator"
							aria-orientation="horizontal"
						>
							<div class="w-8 h-0.5 rounded-full bg-gray-300 dark:bg-gray-600"></div>
						</div>
						<!-- Header -->
						<div class="flex items-center justify-between px-4 py-2 border-b border-gray-100 dark:border-gray-800">
							<div class="flex items-center gap-2">
								<div class="w-6 h-6 rounded-full bg-violet-100 dark:bg-violet-900/30 flex items-center justify-center">
									<svg class="w-3.5 h-3.5 text-violet-600 dark:text-violet-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
									</svg>
								</div>
								<span class="text-sm font-medium text-gray-700 dark:text-gray-300">{$i18n.t('AI Flow Assistant')}</span>
								<div class="ml-2 min-w-[160px]">
									<Selector
										value={aiChatModel}
										items={aiModelOptions.map(m => ({ value: m.id, label: m.label }))}
										size="sm"
										on:change={(e) => { aiChatModel = e.detail.value; }}
									/>
								</div>
							</div>
							<button
								type="button"
								class="p-1 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-400"
								on:click={() => { showAIChat = false; }}
							>
								<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
								</svg>
							</button>
						</div>

						<!-- Messages -->
						<div class="flex-1 overflow-y-auto px-4 py-3 space-y-3">
							{#if aiChatMessages.length === 0}
								<div class="text-center py-6">
									<div class="w-12 h-12 rounded-full bg-violet-50 dark:bg-violet-900/20 flex items-center justify-center mx-auto mb-3">
										<svg class="w-6 h-6 text-violet-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
										</svg>
									</div>
									<p class="text-sm text-gray-500 dark:text-gray-400 mb-3">{$i18n.t('Describe what flow you want to create')}</p>
									<div class="flex flex-wrap gap-1.5 justify-center">
										{#each [
											'고객 문의를 부서별로 분류하는 플로우',
											'가드레일로 PII 검사 후 LLM 응답 생성',
											'입력 감정 분석 → 긍정/부정별 맞춤 응답',
										] as suggestion}
											<button
												type="button"
												class="px-2.5 py-1 text-xs rounded-full border border-violet-200 dark:border-violet-700 text-violet-600 dark:text-violet-400 hover:bg-violet-50 dark:hover:bg-violet-900/20"
												on:click={() => { aiChatInput = suggestion; }}
											>
												{suggestion}
											</button>
										{/each}
									</div>
								</div>
							{/if}

							{#each aiChatMessages as msg}
								<div class="flex {msg.role === 'user' ? 'justify-end' : 'justify-start'}">
									<div class="max-w-[85%]">
										<div class="px-3 py-2 rounded-xl text-sm whitespace-pre-wrap {msg.role === 'user'
											? 'bg-violet-600 text-white rounded-br-sm'
											: 'bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-200 rounded-bl-sm'}">
											{#if msg.loading}
												<div class="flex items-center gap-2">
													<Spinner className="size-4" />
													<span class="text-gray-500">{$i18n.t('Generating flow...')}</span>
												</div>
											{:else}
												{msg.content}
											{/if}
										</div>
										{#if msg.buttons && msg.buttons.length > 0}
											<div class="flex flex-wrap gap-1.5 mt-2">
												{#each msg.buttons as btn}
													<button
														type="button"
														class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg
															border border-violet-200 dark:border-violet-700
															text-violet-700 dark:text-violet-300
															bg-white dark:bg-gray-800
															hover:bg-violet-50 dark:hover:bg-violet-900/20
															hover:border-violet-400 dark:hover:border-violet-500
															transition-all shadow-sm hover:shadow"
														on:click|stopPropagation|preventDefault={() => handleButtonClick(btn.value)}
													>
														{btn.label}
													</button>
												{/each}
											</div>
										{/if}
									</div>
								</div>
							{/each}
						</div>

						<!-- Input -->
						<div class="px-4 py-3 border-t border-gray-100 dark:border-gray-800">
							<div class="flex items-center gap-2">
								<input
									type="text"
									bind:value={aiChatInput}
									on:keydown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendAIChat(); } }}
									class="flex-1 px-3 py-2 text-sm rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-violet-500 focus:border-transparent"
									placeholder={$i18n.t('Describe the flow you want...')}
									disabled={aiChatLoading}
								/>
								<button
									type="button"
									disabled={!aiChatInput.trim() || aiChatLoading}
									class="p-2 rounded-xl bg-violet-600 text-white hover:bg-violet-700 disabled:opacity-50 transition-colors"
									on:click={() => sendAIChat()}
								>
									<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
									</svg>
								</button>
							</div>
						</div>
					</div>
				{/if}
			</div>

			<!-- Right sidebar: Node config -->
			<div class="w-72 border-l border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 overflow-hidden">
				<NodeConfigPanel
					node={selectedNode}
					{upstreamNodes}
					{stateKeys}
					token={localStorage.token}
					currentFlowId={flowId}
					on:update={handleNodeUpdate}
					on:delete={handleNodeDelete}
				/>
			</div>
		</div>
	</div>
{:else}
	<div class="flex items-center justify-center h-full">
		<div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 dark:border-white"></div>
	</div>
{/if}
