"""마켓플레이스 1st-party MCP 서비스의 권위있는 도구 메타데이터 (카테고리 + read_only).

오픈소스 서버 정의에서 생성됨 (버전 핀과 함께 유지):
  - microsoft-365: softeria/ms-365-mcp-server@0.114.0 의 src/endpoints.json
        category = Graph pathPattern, read_only = HTTP method(GET=read) + scopes(.Read vs .ReadWrite/.Send)
  - google-workspace: taylorwilsdon/google_workspace_mcp@1.21.0 소스의
        @handle_http_errors(..., is_read_only=...) 데코레이터 (gmail/calendar 모듈)

read_only: True=read / False=write / None=권위 판별 불가(빈값 → 사용자 설정 또는 AI 분류).
서버 버전 업그레이드 시 위 소스로부터 재생성할 것. 매핑에 없는 도구는 (category=None, read_only=None).
"""

from typing import Optional

MARKETPLACE_TOOL_META: dict[str, dict[str, dict]] = {
    "microsoft-365": {
        "accept-calendar-event": {"category": "Calendar", "read_only": False},
        "add-excel-table-rows": {"category": "Excel", "read_only": False},
        "add-group-member": {"category": "Groups", "read_only": False},
        "add-group-owner": {"category": "Groups", "read_only": False},
        "add-mail-attachment": {"category": "Mail", "read_only": False},
        "add-team-member": {"category": "Teams", "read_only": False},
        "cancel-calendar-event": {"category": "Calendar", "read_only": False},
        "clear-excel-range": {"category": "Excel", "read_only": False},
        "clear-my-presence": {"category": "Presence", "read_only": False},
        "clear-my-user-preferred-presence": {
            "category": "Presence",
            "read_only": False,
        },
        "copy-drive-item": {"category": "Files", "read_only": False},
        "copy-mail-message": {"category": "Mail", "read_only": False},
        "create-calendar": {"category": "Calendar", "read_only": False},
        "create-calendar-event": {"category": "Calendar", "read_only": False},
        "create-chat": {"category": "Chat", "read_only": False},
        "create-contact-child-folder": {"category": "Contacts", "read_only": False},
        "create-contact-folder": {"category": "Contacts", "read_only": False},
        "create-contact-in-folder": {"category": "Contacts", "read_only": False},
        "create-draft-email": {"category": "Mail", "read_only": False},
        "create-drive-item-preview": {"category": "Files", "read_only": True},
        "create-drive-item-share-link": {"category": "Files", "read_only": False},
        "create-excel-chart": {"category": "Excel", "read_only": False},
        "create-excel-table": {"category": "Excel", "read_only": False},
        "create-focused-inbox-override": {"category": "Mail", "read_only": False},
        "create-forward-draft": {"category": "Mail", "read_only": False},
        "create-group": {"category": "Groups", "read_only": False},
        "create-mail-attachment-upload-session": {
            "category": "Mail",
            "read_only": False,
        },
        "create-mail-child-folder": {"category": "Mail", "read_only": False},
        "create-mail-folder": {"category": "Mail", "read_only": False},
        "create-mail-rule": {"category": "Mail", "read_only": False},
        "create-my-calendar-permission": {"category": "Calendar", "read_only": False},
        "create-onedrive-folder": {"category": "Files", "read_only": False},
        "create-onenote-notebook": {"category": "OneNote", "read_only": None},
        "create-onenote-page": {"category": "OneNote", "read_only": None},
        "create-onenote-section": {"category": "OneNote", "read_only": None},
        "create-onenote-section-page": {"category": "OneNote", "read_only": None},
        "create-online-meeting": {"category": "Meetings", "read_only": False},
        "create-outlook-category": {"category": "Mail", "read_only": False},
        "create-outlook-contact": {"category": "Contacts", "read_only": False},
        "create-planner-bucket": {"category": "Planner", "read_only": False},
        "create-planner-task": {"category": "Planner", "read_only": False},
        "create-reply-all-draft": {"category": "Mail", "read_only": False},
        "create-reply-draft": {"category": "Mail", "read_only": False},
        "create-shared-mailbox-draft": {"category": "Mail", "read_only": False},
        "create-sharepoint-list": {"category": "SharePoint", "read_only": False},
        "create-sharepoint-list-column": {"category": "SharePoint", "read_only": False},
        "create-sharepoint-list-item": {"category": "SharePoint", "read_only": False},
        "create-specific-calendar-event": {"category": "Calendar", "read_only": False},
        "create-subscription": {"category": "Subscriptions", "read_only": None},
        "create-team-channel": {"category": "Teams", "read_only": False},
        "create-todo-linked-resource": {"category": "To Do", "read_only": False},
        "create-todo-task": {"category": "To Do", "read_only": False},
        "create-todo-task-list": {"category": "To Do", "read_only": False},
        "create-upload-session": {"category": "Files", "read_only": False},
        "decline-calendar-event": {"category": "Calendar", "read_only": False},
        "delete-calendar": {"category": "Calendar", "read_only": False},
        "delete-calendar-event": {"category": "Calendar", "read_only": False},
        "delete-contact-folder": {"category": "Contacts", "read_only": False},
        "delete-drive-item-permission": {"category": "Files", "read_only": False},
        "delete-excel-range": {"category": "Excel", "read_only": False},
        "delete-excel-table-row": {"category": "Excel", "read_only": False},
        "delete-focused-inbox-override": {"category": "Mail", "read_only": False},
        "delete-group": {"category": "Groups", "read_only": False},
        "delete-mail-attachment": {"category": "Mail", "read_only": False},
        "delete-mail-folder": {"category": "Mail", "read_only": False},
        "delete-mail-message": {"category": "Mail", "read_only": False},
        "delete-mail-rule": {"category": "Mail", "read_only": False},
        "delete-my-calendar-permission": {"category": "Calendar", "read_only": False},
        "delete-onedrive-file": {"category": "Files", "read_only": False},
        "delete-onenote-page": {"category": "OneNote", "read_only": False},
        "delete-online-meeting": {"category": "Meetings", "read_only": False},
        "delete-outlook-contact": {"category": "Contacts", "read_only": False},
        "delete-planner-bucket": {"category": "Planner", "read_only": False},
        "delete-sharepoint-list-column": {"category": "SharePoint", "read_only": False},
        "delete-sharepoint-list-item": {"category": "SharePoint", "read_only": False},
        "delete-specific-calendar-event": {"category": "Calendar", "read_only": False},
        "delete-subscription": {"category": "Subscriptions", "read_only": False},
        "delete-team-channel": {"category": "Teams", "read_only": False},
        "delete-todo-linked-resource": {"category": "To Do", "read_only": False},
        "delete-todo-task": {"category": "To Do", "read_only": False},
        "delete-todo-task-list": {"category": "To Do", "read_only": False},
        "dismiss-calendar-event-reminder": {"category": "Calendar", "read_only": False},
        "download-bytes": {"category": "Files", "read_only": True},
        "extract-drive-item-sensitivity-labels": {
            "category": "Other",
            "read_only": True,
        },
        "find-meeting-times": {"category": "Calendar", "read_only": True},
        "format-excel-range": {"category": "Excel", "read_only": False},
        "forward-calendar-event": {"category": "Calendar", "read_only": False},
        "forward-mail-message": {"category": "Mail", "read_only": False},
        "forward-shared-mailbox-mail": {"category": "Mail", "read_only": False},
        "get-calendar-event": {"category": "Calendar", "read_only": True},
        "get-calendar-view": {"category": "Calendar", "read_only": True},
        "get-channel-files-folder": {"category": "Teams", "read_only": True},
        "get-channel-message": {"category": "Teams", "read_only": True},
        "get-chat": {"category": "Chat", "read_only": True},
        "get-chat-message": {"category": "Chat", "read_only": True},
        "get-current-user": {"category": "Directory", "read_only": True},
        "get-drive-delta": {"category": "Files", "read_only": True},
        "get-drive-item": {"category": "Files", "read_only": True},
        "get-drive-root-item": {"category": "Files", "read_only": True},
        "get-excel-range": {"category": "Excel", "read_only": True},
        "get-excel-table": {"category": "Excel", "read_only": True},
        "get-excel-used-range": {"category": "Excel", "read_only": True},
        "get-group": {"category": "Groups", "read_only": True},
        "get-group-calendar-view": {"category": "Groups", "read_only": True},
        "get-mail-message": {"category": "Mail", "read_only": True},
        "get-mail-message-mime": {"category": "Mail", "read_only": True},
        "get-mail-tips": {"category": "Mail", "read_only": True},
        "get-mailbox-settings": {"category": "Mail", "read_only": True},
        "get-meeting-attendance-report": {"category": "Meetings", "read_only": True},
        "get-meeting-recording": {"category": "Meetings", "read_only": True},
        "get-meeting-recording-content": {"category": "Meetings", "read_only": True},
        "get-meeting-transcript": {"category": "Meetings", "read_only": True},
        "get-meeting-transcript-content": {"category": "Meetings", "read_only": True},
        "get-my-manager": {"category": "Directory", "read_only": True},
        "get-my-presence": {"category": "Presence", "read_only": True},
        "get-onenote-notebook-from-web-url": {"category": "OneNote", "read_only": True},
        "get-onenote-page-content": {"category": "OneNote", "read_only": True},
        "get-online-meeting": {"category": "Meetings", "read_only": True},
        "get-outlook-contact": {"category": "Contacts", "read_only": True},
        "get-planner-bucket": {"category": "Planner", "read_only": True},
        "get-planner-plan": {"category": "Planner", "read_only": True},
        "get-planner-task": {"category": "Planner", "read_only": True},
        "get-planner-task-details": {"category": "Planner", "read_only": True},
        "get-presences-by-user-id": {"category": "Presence", "read_only": True},
        "get-room": {"category": "Places", "read_only": True},
        "get-room-list": {"category": "Places", "read_only": True},
        "get-room-list-room": {"category": "Places", "read_only": True},
        "get-schedule": {"category": "Calendar", "read_only": True},
        "get-sensitivity-label": {"category": "Other", "read_only": True},
        "get-shared-calendar-view": {"category": "Calendar", "read_only": True},
        "get-shared-mailbox-message": {"category": "Mail", "read_only": True},
        "get-sharepoint-list-column": {"category": "SharePoint", "read_only": True},
        "get-sharepoint-site": {"category": "SharePoint", "read_only": True},
        "get-sharepoint-site-by-path": {"category": "SharePoint", "read_only": True},
        "get-sharepoint-site-drive-by-id": {
            "category": "SharePoint",
            "read_only": True,
        },
        "get-sharepoint-site-item": {"category": "SharePoint", "read_only": True},
        "get-sharepoint-site-list": {"category": "SharePoint", "read_only": True},
        "get-sharepoint-site-list-item": {"category": "SharePoint", "read_only": True},
        "get-sharepoint-site-onenote-page-content": {
            "category": "SharePoint",
            "read_only": True,
        },
        "get-sharepoint-sites-delta": {"category": "SharePoint", "read_only": True},
        "get-specific-calendar-event": {"category": "Calendar", "read_only": True},
        "get-specific-calendar-view": {"category": "Calendar", "read_only": True},
        "get-subscription": {"category": "Subscriptions", "read_only": True},
        "get-team": {"category": "Teams", "read_only": True},
        "get-team-channel": {"category": "Teams", "read_only": True},
        "get-todo-task": {"category": "To Do", "read_only": True},
        "get-user-manager": {"category": "Directory", "read_only": True},
        "get-user-presence": {"category": "Presence", "read_only": True},
        "get-virtual-event-webinar": {"category": "Events", "read_only": True},
        "graph-batch": {"category": "Other", "read_only": None},
        "insert-excel-range": {"category": "Excel", "read_only": False},
        "list-all-onenote-sections": {"category": "OneNote", "read_only": True},
        "list-calendar-event-instances": {"category": "Calendar", "read_only": True},
        "list-calendar-events": {"category": "Calendar", "read_only": True},
        "list-calendar-events-delta": {"category": "Calendar", "read_only": True},
        "list-calendar-view-delta": {"category": "Calendar", "read_only": True},
        "list-calendars": {"category": "Calendar", "read_only": True},
        "list-channel-message-hosted-contents": {
            "category": "Teams",
            "read_only": True,
        },
        "list-channel-message-replies": {"category": "Teams", "read_only": True},
        "list-channel-messages": {"category": "Teams", "read_only": True},
        "list-channel-tabs": {"category": "Teams", "read_only": True},
        "list-chat-members": {"category": "Chat", "read_only": True},
        "list-chat-message-hosted-contents": {"category": "Chat", "read_only": True},
        "list-chat-message-replies": {"category": "Chat", "read_only": True},
        "list-chat-messages": {"category": "Chat", "read_only": True},
        "list-chats": {"category": "Chat", "read_only": True},
        "list-contact-folder-child-folders": {
            "category": "Contacts",
            "read_only": True,
        },
        "list-contact-folder-contacts": {"category": "Contacts", "read_only": True},
        "list-contact-folders": {"category": "Contacts", "read_only": True},
        "list-drive-item-permissions": {"category": "Files", "read_only": True},
        "list-drive-item-thumbnails": {"category": "Files", "read_only": True},
        "list-drive-item-versions": {"category": "Files", "read_only": True},
        "list-drives": {"category": "Files", "read_only": True},
        "list-excel-table-rows": {"category": "Excel", "read_only": True},
        "list-excel-tables": {"category": "Excel", "read_only": True},
        "list-excel-worksheets": {"category": "Excel", "read_only": True},
        "list-focused-inbox-overrides": {"category": "Mail", "read_only": True},
        "list-folder-files": {"category": "Files", "read_only": True},
        "list-group-conversations": {"category": "Groups", "read_only": True},
        "list-group-events": {"category": "Groups", "read_only": True},
        "list-group-members": {"category": "Groups", "read_only": True},
        "list-group-owners": {"category": "Groups", "read_only": True},
        "list-group-threads": {"category": "Groups", "read_only": True},
        "list-groups": {"category": "Groups", "read_only": True},
        "list-joined-teams": {"category": "Teams", "read_only": True},
        "list-mail-attachments": {"category": "Mail", "read_only": True},
        "list-mail-child-folders": {"category": "Mail", "read_only": True},
        "list-mail-folder-messages": {"category": "Mail", "read_only": True},
        "list-mail-folder-messages-delta": {"category": "Mail", "read_only": True},
        "list-mail-folders": {"category": "Mail", "read_only": True},
        "list-mail-messages": {"category": "Mail", "read_only": True},
        "list-mail-rules": {"category": "Mail", "read_only": True},
        "list-meeting-attendance-records": {"category": "Meetings", "read_only": True},
        "list-meeting-attendance-reports": {"category": "Meetings", "read_only": True},
        "list-meeting-recordings": {"category": "Meetings", "read_only": True},
        "list-meeting-transcripts": {"category": "Meetings", "read_only": True},
        "list-my-associated-teams": {"category": "Teams", "read_only": True},
        "list-my-calendar-permissions": {"category": "Calendar", "read_only": True},
        "list-my-direct-reports": {"category": "Directory", "read_only": True},
        "list-my-installed-teams-apps": {"category": "Teams", "read_only": True},
        "list-my-memberships": {"category": "Directory", "read_only": True},
        "list-onenote-notebook-sections": {"category": "OneNote", "read_only": True},
        "list-onenote-notebooks": {"category": "OneNote", "read_only": True},
        "list-onenote-pages": {"category": "OneNote", "read_only": True},
        "list-onenote-section-groups": {"category": "OneNote", "read_only": True},
        "list-onenote-section-pages": {"category": "OneNote", "read_only": True},
        "list-online-meetings": {"category": "Meetings", "read_only": True},
        "list-outlook-categories": {"category": "Mail", "read_only": True},
        "list-outlook-contacts": {"category": "Contacts", "read_only": True},
        "list-pinned-chat-messages": {"category": "Chat", "read_only": True},
        "list-plan-buckets": {"category": "Planner", "read_only": True},
        "list-plan-tasks": {"category": "Planner", "read_only": True},
        "list-planner-tasks": {"category": "Planner", "read_only": True},
        "list-relevant-people": {"category": "Directory", "read_only": True},
        "list-room-list-rooms": {"category": "Places", "read_only": True},
        "list-sensitivity-labels": {"category": "Other", "read_only": True},
        "list-shared-calendar-events": {"category": "Calendar", "read_only": True},
        "list-shared-mailbox-folder-messages": {"category": "Mail", "read_only": True},
        "list-shared-mailbox-messages": {"category": "Mail", "read_only": True},
        "list-sharepoint-list-columns": {"category": "SharePoint", "read_only": True},
        "list-sharepoint-site-drives": {"category": "SharePoint", "read_only": True},
        "list-sharepoint-site-items": {"category": "SharePoint", "read_only": True},
        "list-sharepoint-site-list-items": {
            "category": "SharePoint",
            "read_only": True,
        },
        "list-sharepoint-site-lists": {"category": "SharePoint", "read_only": True},
        "list-sharepoint-site-onenote-notebook-sections": {
            "category": "SharePoint",
            "read_only": True,
        },
        "list-sharepoint-site-onenote-notebooks": {
            "category": "SharePoint",
            "read_only": True,
        },
        "list-sharepoint-site-onenote-section-pages": {
            "category": "SharePoint",
            "read_only": True,
        },
        "list-specific-calendar-events": {"category": "Calendar", "read_only": True},
        "list-subscriptions": {"category": "Subscriptions", "read_only": True},
        "list-supported-languages": {"category": "Other", "read_only": True},
        "list-supported-time-zones": {"category": "Other", "read_only": True},
        "list-team-channels": {"category": "Teams", "read_only": True},
        "list-team-members": {"category": "Teams", "read_only": True},
        "list-todo-linked-resources": {"category": "To Do", "read_only": True},
        "list-todo-task-lists": {"category": "To Do", "read_only": True},
        "list-todo-tasks": {"category": "To Do", "read_only": True},
        "list-trending-insights": {"category": "Directory", "read_only": True},
        "list-user-direct-reports": {"category": "Directory", "read_only": True},
        "list-users": {"category": "Directory", "read_only": True},
        "list-webinar-sessions": {"category": "Events", "read_only": True},
        "merge-excel-range": {"category": "Excel", "read_only": False},
        "move-mail-message": {"category": "Mail", "read_only": False},
        "move-rename-onedrive-item": {"category": "Files", "read_only": False},
        "parse-teams-url": {"category": "Teams", "read_only": True},
        "pin-chat-message": {"category": "Chat", "read_only": False},
        "reauthorize-subscription": {"category": "Subscriptions", "read_only": None},
        "remove-group-member": {"category": "Groups", "read_only": False},
        "remove-group-owner": {"category": "Groups", "read_only": False},
        "remove-team-member": {"category": "Teams", "read_only": False},
        "reply-all-mail-message": {"category": "Mail", "read_only": False},
        "reply-all-shared-mailbox-mail": {"category": "Mail", "read_only": False},
        "reply-mail-message": {"category": "Mail", "read_only": False},
        "reply-shared-mailbox-mail": {"category": "Mail", "read_only": False},
        "reply-to-channel-message": {"category": "Teams", "read_only": False},
        "reply-to-chat-message": {"category": "Chat", "read_only": False},
        "reply-to-group-thread": {"category": "Groups", "read_only": False},
        "search-onedrive-files": {"category": "Files", "read_only": True},
        "search-query": {"category": "Search", "read_only": True},
        "search-sharepoint-sites": {"category": "SharePoint", "read_only": True},
        "send-channel-message": {"category": "Teams", "read_only": False},
        "send-chat-message": {"category": "Chat", "read_only": False},
        "send-draft-message": {"category": "Mail", "read_only": False},
        "send-mail": {"category": "Mail", "read_only": False},
        "send-my-activity-notification": {"category": "Teams", "read_only": False},
        "send-shared-mailbox-mail": {"category": "Mail", "read_only": False},
        "set-channel-message-reaction": {"category": "Teams", "read_only": False},
        "set-chat-message-reaction": {"category": "Chat", "read_only": False},
        "set-my-presence": {"category": "Presence", "read_only": False},
        "set-my-status-message": {"category": "Presence", "read_only": False},
        "set-my-user-preferred-presence": {"category": "Presence", "read_only": False},
        "share-drive-item": {"category": "Files", "read_only": False},
        "snooze-calendar-event-reminder": {"category": "Calendar", "read_only": False},
        "sort-excel-range": {"category": "Excel", "read_only": False},
        "tentatively-accept-calendar-event": {
            "category": "Calendar",
            "read_only": False,
        },
        "unmerge-excel-range": {"category": "Excel", "read_only": False},
        "unpin-chat-message": {"category": "Chat", "read_only": False},
        "unset-channel-message-reaction": {"category": "Teams", "read_only": False},
        "unset-chat-message-reaction": {"category": "Chat", "read_only": False},
        "update-calendar": {"category": "Calendar", "read_only": False},
        "update-calendar-event": {"category": "Calendar", "read_only": False},
        "update-contact-folder": {"category": "Contacts", "read_only": False},
        "update-excel-range": {"category": "Excel", "read_only": False},
        "update-excel-table-row": {"category": "Excel", "read_only": False},
        "update-focused-inbox-override": {"category": "Mail", "read_only": False},
        "update-group": {"category": "Groups", "read_only": False},
        "update-mail-folder": {"category": "Mail", "read_only": False},
        "update-mail-message": {"category": "Mail", "read_only": False},
        "update-mail-rule": {"category": "Mail", "read_only": False},
        "update-mailbox-settings": {"category": "Mail", "read_only": False},
        "update-my-calendar-permission": {"category": "Calendar", "read_only": False},
        "update-online-meeting": {"category": "Meetings", "read_only": False},
        "update-outlook-contact": {"category": "Contacts", "read_only": False},
        "update-place": {"category": "Places", "read_only": False},
        "update-planner-bucket": {"category": "Planner", "read_only": False},
        "update-planner-task": {"category": "Planner", "read_only": False},
        "update-planner-task-details": {"category": "Planner", "read_only": False},
        "update-sharepoint-list-column": {"category": "SharePoint", "read_only": False},
        "update-sharepoint-list-item": {"category": "SharePoint", "read_only": False},
        "update-specific-calendar-event": {"category": "Calendar", "read_only": False},
        "update-subscription": {"category": "Subscriptions", "read_only": False},
        "update-team-channel": {"category": "Teams", "read_only": False},
        "update-todo-task": {"category": "To Do", "read_only": False},
        "update-todo-task-list": {"category": "To Do", "read_only": False},
        "upload-file-content": {"category": "Files", "read_only": False},
        "upload-my-profile-photo": {"category": "Directory", "read_only": False},
    },
    "google-workspace": {
        "append_table_rows": {"category": "Sheets", "read_only": None},
        "batch_modify_gmail_message_labels": {"category": "Gmail", "read_only": None},
        "batch_update_doc": {"category": "Docs", "read_only": None},
        "batch_update_form": {"category": "Forms", "read_only": None},
        "batch_update_presentation": {"category": "Slides", "read_only": None},
        "check_drive_file_public_access": {"category": "Drive", "read_only": True},
        "copy_drive_file": {"category": "Drive", "read_only": False},
        "create_calendar": {"category": "Calendar", "read_only": False},
        "create_doc": {"category": "Docs", "read_only": None},
        "create_drive_file": {"category": "Drive", "read_only": None},
        "create_drive_folder": {"category": "Drive", "read_only": None},
        "create_form": {"category": "Forms", "read_only": None},
        "create_presentation": {"category": "Slides", "read_only": None},
        "create_reaction": {"category": "Chat", "read_only": None},
        "create_sheet": {"category": "Sheets", "read_only": None},
        "create_spreadsheet": {"category": "Sheets", "read_only": None},
        "create_table_with_data": {"category": "Docs", "read_only": None},
        "debug_docs_runtime_info": {"category": "Docs", "read_only": True},
        "debug_table_structure": {"category": "Docs", "read_only": True},
        "download_chat_attachment": {"category": "Chat", "read_only": True},
        "draft_gmail_message": {"category": "Gmail", "read_only": None},
        "export_doc_to_pdf": {"category": "Docs", "read_only": None},
        "find_and_replace_doc": {"category": "Docs", "read_only": None},
        "format_sheet_range": {"category": "Sheets", "read_only": None},
        "get_contact": {"category": "Contacts", "read_only": None},
        "get_contact_group": {"category": "Contacts", "read_only": None},
        "get_doc_as_markdown": {"category": "Docs", "read_only": True},
        "get_doc_content": {"category": "Docs", "read_only": True},
        "get_drive_file_content": {"category": "Drive", "read_only": True},
        "get_drive_file_download_url": {"category": "Drive", "read_only": True},
        "get_drive_file_permissions": {"category": "Drive", "read_only": True},
        "get_drive_shareable_link": {"category": "Drive", "read_only": True},
        "get_events": {"category": "Calendar", "read_only": True},
        "get_form": {"category": "Forms", "read_only": True},
        "get_form_response": {"category": "Forms", "read_only": True},
        "get_gmail_attachment_content": {"category": "Gmail", "read_only": True},
        "get_gmail_message_content": {"category": "Gmail", "read_only": True},
        "get_gmail_messages_content_batch": {"category": "Gmail", "read_only": True},
        "get_gmail_thread_content": {"category": "Gmail", "read_only": True},
        "get_gmail_threads_content_batch": {"category": "Gmail", "read_only": True},
        "get_messages": {"category": "Chat", "read_only": None},
        "get_page": {"category": "Slides", "read_only": True},
        "get_page_thumbnail": {"category": "Slides", "read_only": True},
        "get_presentation": {"category": "Slides", "read_only": True},
        "get_spreadsheet_info": {"category": "Sheets", "read_only": True},
        "get_task": {"category": "Tasks", "read_only": None},
        "get_task_list": {"category": "Tasks", "read_only": None},
        "import_to_google_doc": {"category": "Drive", "read_only": None},
        "import_to_google_sheets": {"category": "Drive", "read_only": None},
        "import_to_google_slides": {"category": "Drive", "read_only": None},
        "insert_doc_elements": {"category": "Docs", "read_only": None},
        "insert_doc_image": {"category": "Docs", "read_only": None},
        "inspect_doc_structure": {"category": "Docs", "read_only": True},
        "list_calendars": {"category": "Calendar", "read_only": True},
        "list_contact_groups": {"category": "Contacts", "read_only": None},
        "list_contacts": {"category": "Contacts", "read_only": None},
        "list_docs_in_folder": {"category": "Docs", "read_only": True},
        "list_drive_items": {"category": "Drive", "read_only": True},
        "list_form_responses": {"category": "Forms", "read_only": True},
        "list_gmail_filters": {"category": "Gmail", "read_only": True},
        "list_gmail_labels": {"category": "Gmail", "read_only": True},
        "list_sheet_tables": {"category": "Sheets", "read_only": True},
        "list_spaces": {"category": "Chat", "read_only": None},
        "list_spreadsheets": {"category": "Sheets", "read_only": True},
        "list_task_lists": {"category": "Tasks", "read_only": None},
        "list_tasks": {"category": "Tasks", "read_only": None},
        "manage_conditional_formatting": {"category": "Sheets", "read_only": None},
        "manage_contact": {"category": "Contacts", "read_only": None},
        "manage_contact_group": {"category": "Contacts", "read_only": None},
        "manage_contacts_batch": {"category": "Contacts", "read_only": None},
        "manage_doc_tab": {"category": "Docs", "read_only": None},
        "manage_drive_access": {"category": "Drive", "read_only": False},
        "manage_event": {"category": "Calendar", "read_only": None},
        "manage_focus_time": {"category": "Calendar", "read_only": None},
        "manage_gmail_filter": {"category": "Gmail", "read_only": None},
        "manage_gmail_label": {"category": "Gmail", "read_only": None},
        "manage_out_of_office": {"category": "Calendar", "read_only": None},
        "manage_task": {"category": "Tasks", "read_only": None},
        "manage_task_list": {"category": "Tasks", "read_only": None},
        "modify_doc_text": {"category": "Docs", "read_only": None},
        "modify_gmail_message_labels": {"category": "Gmail", "read_only": None},
        "modify_sheet_values": {"category": "Sheets", "read_only": None},
        "move_sheet_rows": {"category": "Sheets", "read_only": None},
        "query_freebusy": {"category": "Calendar", "read_only": True},
        "read_sheet_values": {"category": "Sheets", "read_only": True},
        "resize_sheet_dimensions": {"category": "Sheets", "read_only": None},
        "search_contacts": {"category": "Contacts", "read_only": None},
        "search_docs": {"category": "Docs", "read_only": True},
        "search_drive_files": {"category": "Drive", "read_only": True},
        "search_gmail_messages": {"category": "Gmail", "read_only": True},
        "search_messages": {"category": "Chat", "read_only": True},
        "send_gmail_message": {"category": "Gmail", "read_only": None},
        "send_message": {"category": "Chat", "read_only": None},
        "set_drive_file_permissions": {"category": "Drive", "read_only": False},
        "set_publish_settings": {"category": "Forms", "read_only": None},
        "update_doc_headers_footers": {"category": "Docs", "read_only": None},
        "update_drive_file": {"category": "Drive", "read_only": False},
        "update_paragraph_style": {"category": "Docs", "read_only": None},
    },
}


def get_tool_meta(service_id: Optional[str], tool_name: str) -> Optional[dict]:
    """(service_id, tool_name) → {category, read_only} 또는 None(미매핑)."""
    if not service_id:
        return None
    return (MARKETPLACE_TOOL_META.get(service_id) or {}).get(tool_name)


# 카테고리 → 필요 OAuth 스코프의 "리소스 prefix" (권위: 위 서버 소스).
#   - microsoft-365: softeria endpoints.json 의 per-endpoint scopes 를 카테고리로 집계한 리소스명
#     (Mail.Read/Mail.Send → "Mail", Files.Read → "Files" ...). prefix 매칭이 스코프 계층
#     (.All / .Shared / Read↔ReadWrite)을 자동 흡수한다. 빈 리스트 = 스코프 불필요(항상 사용 가능).
#   - google-workspace: workspace-mcp auth/scopes.py SCOPE_GROUPS 의 서비스별 스코프 URL prefix.
# 사용자의 granted 스코프(user_oauth_token.scopes) 중 하나라도 prefix 에 걸리면 그 카테고리 사용 가능.
_GOOGLE_AUTH = "https://www.googleapis.com/auth/"
CATEGORY_SCOPE_PREFIXES: dict[str, dict[str, list[str]]] = {
    "microsoft-365": {
        "Mail": ["Mail", "MailboxSettings"],
        "Calendar": ["Calendars"],
        "Contacts": ["Contacts"],
        "Files": ["Files"],
        "Excel": ["Files"],
        "OneNote": ["Notes"],
        "Planner": ["Tasks", "Group"],
        "To Do": ["Tasks"],
        "Directory": ["User", "People", "Directory"],
        "SharePoint": ["Sites"],
        "Groups": ["Group", "GroupMember"],
        # 아래 카테고리는 org-mode 도구 — 필요 스코프가 GRAPH_DELEGATED_SCOPES 에 없으면
        # not_requested(🔴)로 표시된다(admin consent + 앱 등록 + 스코프 추가 필요).
        "Teams": [
            "Team",
            "Channel",
            "ChannelMessage",
            "TeamMember",
            "TeamsActivity",
            "TeamsAppInstallation",
            "TeamsTab",
            "TeamworkTag",
        ],
        "Chat": ["Chat", "ChatMessage", "ChatMember"],
        "Meetings": [
            "OnlineMeetings",
            "OnlineMeetingRecording",
            "OnlineMeetingTranscript",
            "OnlineMeetingArtifact",
        ],
        "Presence": ["Presence"],
        "Places": ["Place"],
        "Events": ["VirtualEvent"],
        "Search": [],  # 검색은 보유 엔티티 스코프로 동작 — 별도 게이트 없음
        "Other": ["User"],
        "Subscriptions": [],  # graph-batch/subscriptions — 별도 스코프 불필요
    },
    "google-workspace": {
        "Gmail": [_GOOGLE_AUTH + "gmail", "https://mail.google.com/"],
        "Calendar": [_GOOGLE_AUTH + "calendar"],
        "Drive": [_GOOGLE_AUTH + "drive"],
        "Docs": [_GOOGLE_AUTH + "documents"],
        "Sheets": [_GOOGLE_AUTH + "spreadsheets"],
        "Slides": [_GOOGLE_AUTH + "presentations"],
        "Forms": [_GOOGLE_AUTH + "forms"],
        "Tasks": [_GOOGLE_AUTH + "tasks"],
        "Contacts": [_GOOGLE_AUTH + "contacts"],
        "Chat": [_GOOGLE_AUTH + "chat"],
    },
}

# M365 granted 스코프가 full-URI 형태(https://graph.microsoft.com/Mail.Read)로 올 때 정규화.
_GRAPH_RESOURCE_PREFIX = "https://graph.microsoft.com/"


def _scope_matches_prefix(scope: str, prefix: str) -> bool:
    """granted 스코프가 카테고리 리소스 prefix 에 속하는지 (계층/한정자 무관)."""
    if not scope:
        return False
    s = scope.strip()
    if s.startswith(_GRAPH_RESOURCE_PREFIX):
        s = s[len(_GRAPH_RESOURCE_PREFIX) :]
    return s == prefix or s.startswith(prefix + ".") or s.startswith(prefix + "/")


def evaluate_category_access(
    service_id: Optional[str],
    category: Optional[str],
    granted_scopes: Optional[list[str]],
    requested_scopes: Optional[list[str]] = None,
) -> dict:
    """카테고리 사용 가능 여부를 granted 스코프 기준으로 판정.

    반환: {"usable": bool|None, "reason": str|None, "needed": list[str]}
      - usable=None  : 판별 불가(미매핑 카테고리 또는 granted 스코프 미상) → UI 배지 미표시
      - reason="not_granted"  : Cloosphere 는 요청하지만 테넌트가 grant 안 함 → 관리자 동의/재로그인 필요
      - reason="not_requested": Cloosphere 가 아예 요청하지 않음 → 스코프 설정 + 앱 등록 추가 필요
      - needed: not_granted 일 때 획득해야 할(우리가 요청 중인) 스코프 목록
    """
    prefixes = (CATEGORY_SCOPE_PREFIXES.get(service_id or "") or {}).get(category or "")
    if prefixes is None:
        return {"usable": None, "reason": None, "needed": []}
    if not prefixes:  # 스코프 불필요
        return {"usable": True, "reason": None, "needed": []}
    if granted_scopes is None:
        return {"usable": None, "reason": None, "needed": []}

    def _any(scopes: list[str]) -> bool:
        return any(_scope_matches_prefix(s, p) for s in scopes for p in prefixes)

    if _any(granted_scopes):
        return {"usable": True, "reason": None, "needed": []}

    requested = requested_scopes or []
    needed = [
        s for s in requested if any(_scope_matches_prefix(s, p) for p in prefixes)
    ]
    if needed:
        return {"usable": False, "reason": "not_granted", "needed": needed}
    return {"usable": False, "reason": "not_requested", "needed": []}
